update_live_price:
  cron: "*/1 * * * *" # Every 10 minutes
  class: "UpdateLivePrice"

delete_expired_event:
  # cron: "0 0 * * *"   # Runs every day at midnight
  cron: "*/60 * * * *" # Every 60 minutes
  class: "DeleteExpiredEvent"
