module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remember a user in a persistent session
  # Encrypts the user id and saves that as a cookie
  # Creates a 'remember_token' cookie using the remember_token generated by Bit64
  # Can't use encrypt, because need to compare it to DB
  def remember(user)
    user.remember
    cookies.permanent.encrypted[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # If there is a active session, set @current_user to that, otherwise search cookies
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.encrypted[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    reset_session
    @current_user = nil
  end
end
